# Generated by Django 3.1.3 on 2023-03-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='workstationuser',
        ),
    ]
